### ISSUE TITLE
Хедер, навбар и футер в отдельные файлы

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-main-page#12]
@Alexander96196

Чтобы исключить копипасту указанных блоков из шаблона в шаблон - я вынес их в отдельные файлы (папка `src/partials/`), которые подключаются во время сборки страниц. Я поправил файлы `src/template.html`, `src/catalog.html`, `src/catalog-list.html` и страницу-пример `sample.html`.

Это не повлияет негативно на пайплайн вашей работы по верстке?

Сорри за то, что вначале вылил, а потом спрашиваю. Но если что - можно откатить )

**Comment by ChesnokovAlexander** [comment]
Все норм, не повлияет)

**Comment by ChesnokovAlexander** [comment]
Обновите ветку, приму изменения.

**Comment by jigius** [comment]
> Обновите ветку, приму изменения.

Она уже обновлена. Единственное я поменял версию загрузчика `html-loader` для webpack'a - нужно будет выполнить `npm i`

**Comment by ChesnokovAlexander** [comment]
Принял
