### ISSUE TITLE
catalog.html - Фильтр - Стрелки

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-main-page#16]
@Alexander96196 
Управления видом стрелок при развертывании/свертывании элементов аккордиона через JS - подход так себе. Цель достигается, но использование таких js-сниппетов в проекте - дополнительная "боль" - это дополнительный каплинг js-кода с шаблоном страницы только лишь для ее представления(внешнего вида), а не на функционал.

Я считаю, что конкретно этот случай можно решить с помощью CSS+HTML. Для этого нужно элемент, который представляет стрелку(`.panel-title::before`) сделать дочерним или соседним от [элемента](https://github.com/jigius/tpl-main-page/blob/cac532300b836af041a98c07a55120847895206e/src/catalog.html#L61) с аттрибутом `data-toggle`. Тогда, для задания стилей для элемента-стрелки можно будет использовать селектор, а котором упоминается или нет класс `collapsed` - изменять ее представление.

Ваше мнение?

**Comment by ChesnokovAlexander** [comment]
Имеете ввиду завернуть например в span и на него навешивать класс? Правильно понимаю?

**Comment by jigius** [comment]
> Имеете ввиду завернуть например в span и на него навешивать класс? Правильно понимаю?

Я имею ввиду создать разметку, которая полагается на поведение BS-плагина collapse.js - при клике на toggle-контролл (в нашем случае это `a[data-toggle="collapse"]`), добавляет или убирает класс `collapsed`. Нужно разместить элемент-стрелку (сейчас это псевдоэлемент `.panel-title::before`) внутри toggle-контролла и настроить для него два css-правила: одно с селектором, в котором присутсвует класс `collapsed`, а во втором - нет. В каждом правиле background-image указывает на разные источники.

Пример с дочерним элементом (я не верстальщик, только для пояснения предложения):

```
<div class="panel-heading">
  <h4 class="panel-title">
    <a class="collapsed" data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="false" aria-controls="collapseOne">
          Цена, ₽
          <span class="hint"></span>
    </a>
  </h4>
</div>
<style>
 .hint {
    background-image: url(arrow-up.svg);
  }
  .collapsed .hint {
    background-image: url(arrow-down.svg);
  }
</style>
```

Можно сделать это  по-разному -  например с использованием элемента-соседа.

### Резюмирую
Таким образом мы дополнительно не "навешиваем" свои классы на элементы и не доьавляем свои обрабочики событий, а полагаемся на поведение плагина, которое хорошо документировано и известно разрабочикам.

**Comment by ChesnokovAlexander** [comment]
Понял, поправлю

**Comment by ChesnokovAlexander** [comment]
Готово
