### ISSUE TITLE
/moods/modal-popup.html

### ISSUE THREAD

**Issue by dorohinsa** [jigius/tpl-main-page#20]
Поправить отступы .modal-content
https://i.imgur.com/v2GTMtz.png

Убрать отступ .modal-header-*::before
https://i.imgur.com/gZwztuF.png

Добавить отступ .modal-title
https://i.imgur.com/iBU0B9f.png

Результат в большом разрешении:
https://i.imgur.com/aZbmMW2.png

**Comment by ChesnokovAlexander** [comment]
Готово
