### ISSUE TITLE
CSS styles 11-21 

### ISSUE THREAD

**Issue by dorohinsa** [jigius/tpl-main-page#22]
== Глобальные стили
Убрать фиксированную ширину обертки контента модального окна для ширины окна >1200
@media (min-width: 1200px)
.modal-content {
    /* width: 694px; */
}

Исправить дефолтный цвет ховера и фокуса ссылок
a:hover, 
a:focus {
  color: initial;
}

Добавить внешнюю линию для ссылок и кнопок в фокусе
a:focus, button:focus {
outline: solid #767676 1px !important;
}

Поправить цвет чекбокса в фокусе
.check-input:focus + .check-box {
  border: 1px solid #333;
}

Сделать стиль рамки в фокусе для select так же как input type="text" 
https://i.imgur.com/5uSPUQm.png

== order.html
Добавить кнопку "Отмена" слева от "Заказ"
Стиль как кнопка "No" в модальных окнах.

== catalog.html
Изменить отображение полос прокрутки для .panel-body в блоке фильтра.
Не понятно, зачем отступ справа?
https://i.imgur.com/vMse8YE.png

В ФаерФоксе поля фильтра по цене выходят за рамки блока. Нужно колдовать с отступами и шириной лейблов, инпутов.

**Comment by ChesnokovAlexander** [comment]
Готово

**Comment by jigius** [comment]
@Alexander96196 Где пулл-реквест?

**Comment by ChesnokovAlexander** [comment]
Отправил
