### ISSUE TITLE
all-pages / main blocks css classes

### ISSUE THREAD

**Issue by dorohinsa** [jigius/tpl-main-page#26]
Структура основных блоков сайта должна быть одинаковой на всех страницах.
Сайт делится на 3 основных блока: шапка, средняя часть (контент), подвал.
Контентная часть сейчас в основном в такой структуре, но для каждой страницы определены свои классы:
main
 section
  div.container

Классы этих элементов не должны быть привязаны к разделу. 
Например, сейчас: 
<section class="order">

В блоке контента, элементы которые присутствуют на всех страницах (крошки, заголовок) так же должны иметь универсальный класс, не привязанный к разделу или не иметь классы. Например, сейчас:
<h1 class="order-title">

В итоге элементы в блоке контента не должны зависеть от наличия классов в main, section и других обертках, которые определяют область между шапкой и подвалом.

**Comment by ChesnokovAlexander** [comment]
https://github.com/jigius/tpl-main-page/pull/38

**Comment by jigius** [comment]
@dorohinsa проверь результат. Я слил пулл-реквест пока только с тестовой веткой `foo`

Сделай у себя:
```
git fetch origin foo
git checkout foo
npm run build
```

**Comment by dorohinsa** [comment]
Посмотрел тестовую, классы на тегах <section> все еще есть, но они не привязаны к вложенным элементам. 
Универсальная обертка будет выглядеть как. 
main.main
  section
    div.row

**Comment by dorohinsa** [comment]
@Alexander96196 Посмотри телефон в шапке, не вмещается в одну на ширину экрана >1520px

**Comment by ChesnokovAlexander** [comment]
@dorohinsa Ок, посмотрю

**Comment by dorohinsa** [comment]
> @dorohinsa Ок, посмотрю
На ширине экрана 1920 пикс, кнопка и номер телефона неправильно выглядят
https://i.imgur.com/CB1EPjL.png

**Comment by ChesnokovAlexander** [comment]
https://github.com/jigius/tpl-main-page/pull/41
