### ISSUE TITLE
catalog.html / Add pagination

### ISSUE THREAD

**Issue by dorohinsa** [jigius/tpl-main-page#27]
Добавить пагинацию.
Замени <p> на <span>:
 <span class="catalog-pages">                
 Показано с 1 по 3 из 3 (всего страниц: 1)            
 </span>

На страницу каталога добавить строку с пагинацией. 
https://getbootstrap.com/docs/3.3/components/#pagination-default

https://i.imgur.com/KqRFtiZ.png

**Comment by ChesnokovAlexander** [comment]
Готово 
https://github.com/jigius/tpl-main-page/pull/33

**Comment by ChesnokovAlexander** [comment]
Готово
https://github.com/jigius/tpl-main-page/pull/37
