### ISSUE TITLE
order.html / checkbox  .has-error css styles

### ISSUE THREAD

**Issue by dorohinsa** [jigius/tpl-main-page#29]
В чекбоксах может использоваться класс .has-error, для подсветки в каких чекбоксах есть проблема.
Который меняет цвет квадрата чекбокса на #E01F35
В постановке задачи на страницу заказа есть перечень классов на разные состояния.

**Comment by ChesnokovAlexander** [comment]
Готово 
https://github.com/jigius/tpl-main-page/pull/32

**Comment by jigius** [comment]
@Alexander96196 Я принял твой пул-реквест и откатил назад (( 

`has-error` в бутстрапе - класс который используется для задания признака ошибки у контролла формы и добавляется он (по-крайне мере так у нас сейчас в проекте) к контейнеру контролла, у которого  селектор `.form-group` ( примеры использования - `order.html`). 

Я обновил страницу `order.html` - добавил класс `has-error` для последнего чекбокс-контролла формы. 

Твоя задача - сделать так, чтобы последний чекбокс показывался с красными границами - как сейчас показываются  контроллы `select` и `input`.

PS.  Нужно забрать мои правки перед началом работ

**Comment by ChesnokovAlexander** [comment]
Принял

**Comment by Alexander96196** [comment]
https://github.com/jigius/tpl-main-page/pull/36

**Comment by ChesnokovAlexander** [comment]
https://github.com/jigius/tpl-main-page/pull/39
