### ISSUE TITLE
правки фала - src/js/common.js

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-main-page#7]
@Alexander96196 

Правки случайные? Я верно понял, что это IDE переформатировал автоматом?

**Comment by ChesnokovAlexander** [comment]
Нет, там пару скриптов. Для переворота стрелки в аккордеоне и замена текста в кнопке при открытии "Фильтр", "Скрыть фильтр".

**Comment by jigius** [comment]
Просто весь файл переформатирован, и diff'ом сложно увидеть реальные внесенные правки - файл большой и для этого придется вчитываться.... Проще спросить )) Туда добавлен новый чанк кода, но оригинальный код там не изменен?

**Comment by jigius** [comment]
Этот чанк, верно?
```
const btn = document.querySelector(".btn > span");
  btn.addEventListener("click", function () {
    btn.innerHTML =
      btn.innerHTML === "Фильтр"
        ? (btn.innerHTML = "Скрыть фильтр")
        : (btn.innerHTML = "Фильтр");
  });

  $(document).ready(function () {
    $(".panel-title").click(function (event) {
      $(this).toggleClass("active").next().slideToggle(300);
    });
  });
```

**Comment by jigius** [comment]
Только этот код был добавлен, верно?
```
$(".btn").click(function () {
    var $btn = $(this);
    var text = $btn.text();
    var label = $btn.data("label");

    $btn.text(label).data("label", text);
  });

  $(document).ready(function () {
    $(".panel-title").click(function (event) {
      $(this).toggleClass("active").next().slideToggle(300);
    });
  });
```

**Comment by ChesnokovAlexander** [comment]
Да все верно, только этот. Значит переформатировался автоматом как и писали вначале)
Если, что буду добавлять в самый конец код. Буду тогда комментировать код, чтобы было понятно.

**Comment by jigius** [comment]
Никаких правил по добавлению js-кода при верстке, с нашей стороны, к сожалению, не было предоставлено :(

Такие правила я добавил [здесь](https://github.com/jigius/tpl-main-page/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-js-%D0%BA%D0%BE%D0%B4%D0%B0-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83). 

Твой код, согласно правилам, я перенес в файл `src/js/page/catalog/filter.js`. Страница работает.
